version: '3.9'

# Builds a production bundle and starts an Nginx server to deliver it
services:
  app:
    build:
      context: .
      dockerfile: config/docker/build-and-deploy.Dockerfile
    container_name: angular_app_prod
    ports:
      - "9200:80"
