version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: config/docker/development.Dockerfile
    command: sh -c "npm start"
    ports:
      - "5200:4200"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules

volumes:
  node_modules:
